### ISSUE TITLE
论文中提到map采用的是map50还是map50-95?

### ISSUE THREAD

**Issue by zhangshoulong** [SunYM2020/UA-CMDet#16]
论文中提到map采用的是map50还是map50-95?
![image](https://user-images.githubusercontent.com/52525731/235567647-cfbf54f5-04dd-4bd7-9743-4d85aaa9a609.png)

**Comment by wxh1402714457** [comment]
我也想问这个问题，mAP值太高了，感觉是mAP50？请问作者这个mAP具体来说是哪一种呢？mAP50还是mAP50-95?

**Comment by yaoergogo** [comment]
> 我也想问这个问题，mAP值太高了，感觉是mAP50？请问作者这个mAP具体来说是哪一种呢？mAP50还是mAP50-95？

所以是50吗，想确认一下

**Comment by SunYM2020** [comment]
论文中使用的都是mAP50
