### ISSUE TITLE
两种模态图片的对齐代码能开源吗？

### ISSUE THREAD

**Issue by zhangshoulong** [SunYM2020/UA-CMDet#17]
两种模态图片的对齐代码能开源吗？

**Comment by csy0821** [comment]
你好，请问您解决了吗？我也没有在UA-CMDet中找到实现UAM模块的代码，没看到有不确定权重的实现部分。
感谢您的回答。

**Comment by SunYM2020** [comment]
> 你好，请问您解决了吗？我也没有在UA-CMDet中找到实现UAM模块的代码，没看到有不确定权重的实现部分。 感谢您的回答。

Please refer to "UA-CMDet/mmdet/models/detectors/UACMDet.py".
