### ISSUE TITLE
数据集中的JSon文件缺失

### ISSUE THREAD

**Issue by Heedsosogood** [SunYM2020/UA-CMDet#2]
对应数据集中的JSon文件缺失，只有XML文件，好像XML文件对不上号无法转JSON

**Comment by SunYM2020** [comment]
请注意，DroneVehicle数据集仅采用voc格式标注。我转了coco格式的标注，有需要可以留一下你的邮箱

**Comment by Heedsosogood** [comment]
> 请注意，DroneVehicle数据集仅采用voc格式标注。我转了coco格式的标注，有需要可以留一下你的邮箱

我的邮箱是827628228@qq.com 十分感谢 期待分享！

**Comment by lxc741** [comment]
您好，可以也给我分享一份吗？我的邮箱865441214@qq.com  万分感谢！！！

**Comment by Heedsosogood** [comment]
你好，我训练出结果后无法进行评估， 请问test.py怎么运行出results.pkl文件呢，Task1_results是通过parse_result文件获得的吗？我对这个项目的测试和评估不太理解，希望能得到您的解答~




尼克
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "SunYM2020/UA-CMDet"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月3日(星期六) 凌晨1:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [SunYM2020/UA-CMDet] 数据集中的JSon文件缺失 (Issue #2)





 
Closed #2 as completed.

**Comment by SunYM2020** [comment]
运行 python tools/test.py configs/DroneVehicle/UACMDet.py work_dirs/UACMDet/epoch_12.pth --out work_dirs/UACMDet/results.pkl 即可

**Comment by Heedsosogood** [comment]
我已导出一版'DV_val.json等文件并运行出结果，还想最后请教您最后两个问题。
1.数据集的评估是怎么根据rgb图像的bbox评估的还是infrared的标注评估的，
我在rbg图像map为67红外为72，与论文中的64不符。
2.根据问题一，看到您有在git上更新代码，只输出fusion进行IA_nms，是不是这个原因呢
期待解答！

**Comment by SunYM2020** [comment]
1、我们仅使用红外图像的标注作为最终评估的GT；
2、不太清楚你的红外和可见光图像的mAP是分别用各自模态的gt算出来的吗，我是用了fusion的结果与红外gt算的最终结果。

**Comment by SunYM2020** [comment]
为了便于检测图像边缘截断处的目标，我们论文里的结果是在包含白边的图像上测试的。但是在数据集开源后很多人对我们数据集设置白边不理解，目前开源的代码里面在训练和测试时候都是去除白边的。
【这里给出设置白边的目的：1、方便标注人员标注图像边缘截断的目标；2、方便对图像边缘截断目标进行检测的需求】

**Comment by oneac** [comment]
> Owner
你好，可以也给我分享一下那个标注格式转换的嘛？我的邮箱是2182983902@qq.com,谢谢，谢谢，十分感谢

**Comment by rubbish-qi** [comment]
你好，可以也给我分享一下那个标注格式转换的嘛？我的邮箱是[980354455@qq.com](mailto:980354455@qq.com),谢谢，谢谢，十分感谢

**Comment by Porphy** [comment]
你好，可以也给我分享一下那个标注格式转换的嘛？我的邮箱是1838061436@qq.com,谢谢，谢谢，十分感谢

**Comment by SunYM2020** [comment]
> Annotation files in COCO format can be downloaded in the [link](https://pan.baidu.com/s/1k0WdfqDgwloQn4xfKfmNFA?pwd=x742). (extracting code: x742)

**Comment by challow0** [comment]
> 我已导出一版'DV_val.json等文件并运行出结果，还想最后请教您最后两个问题。 1.数据集的评估是怎么根据rgb图像的bbox评估的还是infrared的标注评估的， 我在rbg图像map为67红外为72，与论文中的64不符。 2.根据问题一，看到您有在git上更新代码，只输出fusion进行IA_nms，是不是这个原因呢 期待解答！

您好，我测出来的结果跟你之前实验的一致（rgb 67 ir 72），请问是哪里出问题了吗？
