### ISSUE TITLE
请问用的这个显卡型号是多少

### ISSUE THREAD

**Issue by mujianyu** [SunYM2020/UA-CMDet#24]
我有一个3060和一个4070结果两个报了RuntimeError: cublas runtime error : the GPU program failed to execute at /tmp/pip-req-build-jh50bw28/aten/src/THC/THCBlas.cu:259的错误，我问了其他人，他们说是因为高版本的RTX不能支持低版本的cuda10.0，虽然理论上是可以的

**Comment by medicineqian** [comment]
请问你解决了吗，3060和3090也有同样的错误

**Comment by mujianyu** [comment]
没有

**Comment by SunYM2020** [comment]
应该是在2080ti

**Comment by Zshuting** [comment]
请问现在解决了吗？我用3090也错了 报错RuntimeError: CUDA error: no kernel image is available for execution on the device
