### ISSUE TITLE
论文中的不确定性权重ωinf，ωrgb这些的值是怎么分配的？随机吗

### ISSUE THREAD

**Issue by leileilei2000** [SunYM2020/UA-CMDet#28]

**Comment by csy0821** [comment]
您能好，请问您解决了吗？我也没有在UA-CMDet中找到关于UAM模块的代码，没看到不确定权重wi   wr   wf 的实现部分。
感谢您的回答。

**Comment by SunYM2020** [comment]
Please refer to "UA-CMDet/mmdet/models/detectors/UACMDet.py".
