### ISSUE TITLE
No module named 'DOTA_devkit'

### ISSUE THREAD

**Issue by longkex** [SunYM2020/UA-CMDet#29]
![image](https://github.com/SunYM2020/UA-CMDet/assets/51194655/43601cf9-c118-4bf5-a431-3aa19946047a)

**Comment by SunYM2020** [comment]
Please refer to [DOTA_devkit](https://github.com/CAPTAIN-WHU/DOTA_devkit). Put the folder “DOTA_devkit” into the “UA-CMDet/”.
