### ISSUE TITLE
show_result.py可视化问题

### ISSUE THREAD

**Issue by Heedsosogood** [SunYM2020/UA-CMDet#3]
我用show_result.py函数可视化出现下面这个问题

 assert bboxes.shape[1] == 4 or bboxes.shape[1] == 5
AssertionError
这个项目是否有可视化文件呢？
期待您的回复。
如果方便的话想加您联系方式，我的VX：HeXiao9968  qq：827628228
邮箱：827628228@qq.com

**Comment by SunYM2020** [comment]
我没有使用过show_result.py，结果可视化需要自行修改了

**Comment by Heedsosogood** [comment]
感谢回复~
&nbsp;


尼克
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月5日(星期一) 下午2:58
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [SunYM2020/UA-CMDet] show_result.py可视化问题 (Issue #3)





 
我没有使用过show_result.py，结果可视化需要自行修改了
