### ISSUE TITLE
请问这个是什么原因呢，assert shape[i] >= img.shape[i]

### ISSUE THREAD

**Issue by longkex** [SunYM2020/UA-CMDet#30]
![image](https://github.com/SunYM2020/UA-CMDet/assets/51194655/8390a80d-2c31-4acf-8a2d-1728cddc8827)

**Comment by SunYM2020** [comment]
我没有遇到这个问题，感觉像是维度上不匹配，可以单步调试一下shape，看看哪里出了问题
