### ISSUE TITLE
import DOTA_devkit.polyiou as polyiou

### ISSUE THREAD

**Issue by Blissy-32** [SunYM2020/UA-CMDet#32]
import DOTA_devkit.polyiou as polyiou  这个显示没有DOTA_devkit.polyiou，已经执行了install里的指令，请问是为什么

**Comment by Zshuting** [comment]
请问是要执行pip install DOTA_devkit 执行后可以接着运行吗？因为我在网上找的是DOTA_devkit不是一个包

**Comment by SunYM2020** [comment]
You can refer to [issue](https://github.com/SunYM2020/UA-CMDet/issues/29#issuecomment-2080920085).
