### ISSUE TITLE
problems of evaluation

### ISSUE THREAD

**Issue by Murphy122** [SunYM2020/UA-CMDet#5]
Hi , I'm interested in  your work UA-CMDet and your Dataset DroneVehicle. I also do some simple experoments on DroneV Dataset.But when it comes to evaluation, I could only get eval results on VOC mAP, which is better than your score even using two stream Faster R-CNN. So I wonder how to get you score. 
**Do you eval your work on COCO AP**? I wonder how to get the score of 64.01.
One possible resolution is to use COCO segment evaluation, and I tried to eval my result on COCO segms, but the AP50:95 seems to be even lower than that in your paper using single modality. Something might go wrong. 
I can't find details on your code about evaluation. Since the work environment of your code is pretty old, I can't run your code on my own works station.But I have found something in your code.In 
[https://github.com/SunYM2020/UA-CMDet/blob/main/mmdet/models/detectors/UACMDet.py](url) , line 754 ,
`
 #type ---> list
        rbbox_results_fusion = dbbox2result(det_rbboxes_fusion, det_labels_fusion,
                                     self.rbbox_head_f.num_classes)
        return rbbox_results_fusion
`
I found the output of **simple_test** is a list. But in 
[https://github.com/SunYM2020/UA-CMDet/blob/main/mmdet/core/evaluation/coco_utils.py](url) line 141, 
`def results2json(dataset, results, out_file):
    if isinstance(results[0], list):
        json_results = det2json(dataset, results)
    elif isinstance(results[0], tuple):
        json_results = segm2json(dataset, results)
    elif isinstance(results[0], np.ndarray):
        json_results = proposal2json(dataset, results)
    else:
        raise TypeError('invalid type of results')
    mmcv.dump(json_results, out_file)`
your code seems to execute the function **det2json** , which only contains HBB bbox evaluation. These code makes me very confused. 
All I wish is to compete with your work in the same way, so can you give me some advice on the following topic:

1. How to Configure the operating environment to run your code 
2. How do you evaluate the output of Networks and get the result  64.01.

Looking forward to your reply！

**Comment by SunYM2020** [comment]
Thanks for your attention to our work!
1. Please refer to [INSTALL.md](https://github.com/SunYM2020/UA-CMDet/blob/main/INSTALL.md) for configuring the operating environment.
2. We use the VOC 07 metric. You can install and run our code according to the [README.md](https://github.com/SunYM2020/UA-CMDet/blob/main/README.md). Please refer to [DroneVehicleEval.py](https://github.com/SunYM2020/UA-CMDet/blob/main/eval/DroneVehicleEval.py) for the evaluation.
