### ISSUE TITLE
obb和hbb在YOLO系列上的map差距

### ISSUE THREAD

**Issue by neuhsm** [SunYM2020/UA-CMDet#6]
你好，我在尝试使用yolov7训练这个数据集，我将标注转换成了hbb的标注进行训练，按照原始数据集划分训练，在验证集上有67%的map（还在继续训练，map还在缓慢上升），但是在测试集上map只有22%，不知道是由于测试集和验证集间差异导致map差距还是由于我将obb转换成了hbb导致的。

**Comment by neuhsm** [comment]
使用的代码来自 https://github.com/bubbliiiing/yolov7-pytorch ，训练前30个epoch时冻结主干，后面训练整个网络

**Comment by neuhsm** [comment]
![00139](https://user-images.githubusercontent.com/76637172/210160236-ab9518a8-922e-4eec-9782-cda9dcf4a9a4.png)
这是在测试集上的一个检测效果，第139张图，我认为训练过程应该没有问题

**Comment by neuhsm** [comment]
这个问题解决了，不知道你有没有测试过hbb标注的一些算法map的baseline

**Comment by supercpy** [comment]
> 这个问题解决了，不知道你有没有测试过hbb标注的一些算法map的baseline

你好，请问你在UA-CMDet用hbb实验了吗

**Comment by SunYM2020** [comment]
不好意思，没有对这个进行过探索
