### ISSUE TITLE
coco标注数据可能上传错文件了

### ISSUE THREAD

**Issue by VickyLuokang** [SunYM2020/UA-CMDet#8]
coco标注文件中类别只有DV_train.json的category_id只有1，2，3，没有4和5。另外训练数据集的xml标注中也存在错误

**Comment by SunYM2020** [comment]
> coco标注文件中类别只有DV_train.json的category_id只有1，2，3，没有4和5。另外训练数据集的xml标注中也存在错误

In the uploaded DV_train.json, ["category_id": 5] has 7275 and ["category_id": 4] has 10421, there may be a problem with your statistics, please recheck.

**Comment by SunYM2020** [comment]
The problem in the xml file is corrected in the COCO format annotation.
