### ISSUE TITLE
关于测试集的JSON文件

### ISSUE THREAD

**Issue by BlackLotus12138** [SunYM2020/UA-CMDet#9]
想问一下为什么源代码中的测试用的是验证集？
如果可以的话，能否分享一下测试集的标签的JSON文件？
万分感谢！

**Comment by SunYM2020** [comment]
> 想问一下为什么源代码中的测试用的是验证集？ 如果可以的话，能否分享一下测试集的标签的JSON文件？ 万分感谢！

We have updated the annotations in json format for testing on github.
